### PR TITLE
MediaFilterGraph.AddAudioBufferSource add colorsapce params

### PR DESCRIPTION
**Pull request by RyanYANG52**
Hi @dubiousconst282 , I am try to impl a auto rotate filter like ffmpeg cli does, [ffplay](https://github.com/FFmpeg/FFmpeg/blob/8670615743eb36d7b3e9b522266518796df7ec54/fftools/ffplay.c#L1963)  [ffmpeg](https://github.com/FFmpeg/FFmpeg/blob/8670615743eb36d7b3e9b522266518796df7ec54/fftools/ffmpeg_filter.c#L1711)

I got some warning for some video file when using `AddVideoBufferSource`

```
Changing video frame properties on the fly is not supported by all filters.
filter context - w: 1920 h: 1080 fmt: 0 csp: unknown range: unknown, incoming frame - w: 1920 h: 1080 fmt: 0 csp: bt709 range: tv pts_time: 0.0208
```

So I add a colorspace params, but couple things I am not sure, can you review it

1. should I make it a breaking change, make colorspace not optional?
2. `AddVideoBufferSource`'s frameRate I use in the `DecodeFilterVideo` demo it's coming from decoder (copy from stream->codecpar->framerate), I am not sure if that is correct. I see [ffplay](https://github.com/FFmpeg/FFmpeg/blob/8670615743eb36d7b3e9b522266518796df7ec54/fftools/ffplay.c#L1898) omit frame rate

---

Also I want to add create auto rotation filter logic into the codebase, It can be use in VideoFrame.Save, or use in transcode task. But I don't know if that is something needed, and if so where should I put it. You can impl yourself if you want of course, packet 
display matrix side data can come from avstream, avpacket or avframe

---

Another thing I impl in my codebase I think is useful is Log setting, I copy from https://github.com/IOL0ol1/EmguFFmpeg/blob/dev/src/Utilities/FFmpegLog.cs, for none console app it would be useful to log to somewhere else. Though I do not know how to name this class in this project

### CODE REVIEW

**Comment by dubiousconst282** [comment]
Thank you, here's my thoughts:
- I think breaking the API would be fine, and maybe even better since it might help prevent that warning from triggering for future users.
- `GuessFrameRate()` looks preferable as it seems to handle most of the [weird edge cases](https://github.com/FFmpeg/FFmpeg/blob/7b47099bc080ee597327476c0df44d527c349862/libavformat/avformat.c#L750) and some more (it also seems to be [what ffplay](https://github.com/FFmpeg/FFmpeg/blob/8670615743eb36d7b3e9b522266518796df7ec54/fftools/ffplay.c#L1868) is using), but I think wrapping the other fields too doesn't hurt.
- I suppose having something like `VideoFrame.NormalizeDisplayMatrix()` or maybe `CopyRotatedFrom()` would probably be the most convenient to use and require the least changes from what I can guess, but it might be difficult to optimize if the filters are expansive to instantiate per call. Maybe a class like SwScaler would work better in that case?
- The logging setting would be nice to have (not sure about a good place for it either, maybe on a more generic static class like `FFmpegUtils`?)

**Comment by dubiousconst282** [comment]
(Mostly unrelated to this PR, but I think having a more abstract filter graph API that is just "Filter()" plus a few static factory methods for common stuff like CreateFromString(), CreateRotate(), and CreateColorspace(), would possibly cover most use cases too. I'd like to look into this later but feel free to share any thoughts.)

**Comment by RyanYANG52** [comment]
I think most of user case will be able to get display matrix before decoding or after the first packet arrived, and stay the same for all the packets in the same stream. Swscaler approach would be preferable than `VideoFrame.NormalizeDisplayMatrix()`

*more abstract filter graph API* would be nice, maybe like a `VideoFilterBuilder`, can add rotate, scale, zscale, etc, then Build(), but I am not sure, feels like too much case to cover. Maybe just add some helper method or class (FilterStringBuilder maybe) into current filter API and some demo would be enough to cover most use cases.

I add some logic from my code into FrameExtractor demo for reference, you can test with a smartphone vertical recorded video, somepart may go into codebase.

`FFmpegUtils` sounds good, in the future can add more method like check version, get available codec, global setting, etc.

Overall, maybe you can take over from here, I can give your some suggestions along the way 😊

**Comment by dubiousconst282** [comment]
I went ahead and extended `AutoRotator` into `VideoFilterPipeline`, along with a static CreateAutoRotate() method. I plan to add extensions like CreateZscale() later, but it can also take arbitrary graph strings, which I believe to be enough to cover most use cases around graphs with one input and output.

Let me know what you think :)

**Comment by RyanYANG52** [comment]
look great! 
Only one thing I am not sure is how user would chain video filter together. 

If you add CreateZscale or other extensions, it would be independent from each other. I suppose user can create a new buffer src from previous VideoFileterPipeline'sink, then PictureColorspace should be exposed from VideoBufferSink. FFmpeg only add `av_buffersink_get_color_range` and `av_buffersink_get_colorspace` [recently](https://github.com/FFmpeg/FFmpeg/blob/8cea66a73c52572f4ac6c552f654e44e8ba55849/doc/APIchanges#L136), this is no way to get or set `color_trc` and `color_primaries`. So maybe add a structure only have matrix and range and can implicit convert from PictureColorspace, or user can lazy create the second filter after first filter apply once

Of course, User can also concat filter description them-self, by call `GetAutoRotateFilterString`

**Comment by dubiousconst282** [comment]
Yes that would be a problem. Concating the filter strings would work, but I'm thinking a builder pattern would be more idiomatic in a way. Maybe something like:

```cs
VideoFilterPipeline.CreateBuilder()
    .BufferSource(...)
    .AutoRotate(...)
    .ZScale(...)
    .Build();
```

**Comment by RyanYANG52** [comment]
ideally builder pattern is perfect for pipeline, `AutoRotate` would be tricky, it feels more like a options `autoRotate` for mediaStream `BufferSource` (for hw buffer source, I am not sure)

https://ffmpeg.org/ffmpeg.html#Video-Options

```
-vf filtergraph (output)
Create the filtergraph specified by filtergraph and use it to filter the stream.

This is an alias for -filter:v, see the [-filter option](https://ffmpeg.org/ffmpeg.html#filter_005foption).

-autorotate
Automatically rotate the video according to file metadata. Enabled by default, use -noautorotate to disable it.
```

Also `AutoRotate` could result into 0-2 filters, maybe add a filter count check prop?

**Comment by RyanYANG52** [comment]
And I guess if you also add `.SwScale` for `VideoFilterPipelineBuilder`, it can be used as a advanced version of swscaler, `crop` `hue` can be added in the future as well

**Comment by dubiousconst282** [comment]
I've just pushed an initial implementation of the new builder API, I think it is ready to merge if you don't have any concerns.

Apologies for the long delay.

---

Initially I was going to keep the original restriction of one input only, but I realized that it would not be hard to extend to support most (if not all) of the filter graph API capabilities using string port names, and I think a bit more succinct to use compared to the current node API (although it may still be better suitable for more dynamic scenarios like UIs).

I felt that enabling auto rotate by default would add hidden complexity for properties like `decoder.FrameFormat`, so I keept it as a required parameter and added another overload with an extra byref size parameter that is rotated accordingly, as that might be useful for subsequent filters like swscale (most filters can also accept string expressions that are given the input node dimensions and evaluated per graph config() or filtered frame, but that is probably best left for `Segment()`).

Another concern was that short graphs with no filters added other than auto rotate could be empty, but I have verified that there is no significant performance impact in calling Apply() in that case, as frame data is propagated without being copied.

**Comment by RyanYANG52** [comment]
Looks great, add autorotate into `Builder.VideoBufferSource` and allow multiple input make sense, I think it is ready to merge

**Pull request merged**
